# Generated by Django 3.2.25 on 2024-04-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0002_alter_tournoi_type_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='gagnant',
        ),
        migrations.RemoveField(
            model_name='match',
            name='equipe1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='equipe2',
        ),
        migrations.RemoveField(
            model_name='tournoi',
            name='matchs',
        ),
        migrations.AddField(
            model_name='match',
            name='equipe1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchs_as_e1', to='tournois.equipe'),
        ),
        migrations.AddField(
            model_name='match',
            name='equipe2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchs_as_e2', to='tournois.equipe'),
        ),
        migrations.AddField(
            model_name='match',
            name='score_equipe1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_equipe2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='tournoi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournois.tournoi'),
            preserve_default=False,
        ),
    ]
