# Generated by Django 3.2.25 on 2024-04-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0004_joueur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joueur',
            name='numero',
        ),
    ]
